export const GET_ALL_MOVIES_REQUEST = 'GET_ALL_MOVIES_REQUEST'
export const GET_ALL_MOVIES_SUCCESS = 'GET_ALL_MOVIES_SUCCESS'
export const GET_ALL_MOVIES_FAILURE = 'GET_ALL_MOVIES_FAILURE'

export const GET_MOVIE_DETAILS_REQUEST = 'GET_MOVIE_DETAILS_REQUEST'
export const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS'
export const GET_MOVIE_DETAILS_FAILURE = 'GET_MOVIE_DETAILS_FAILURE'

export const ADD_MOVIE_REQUEST = 'ADD_MOVIE_REQUEST'
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS'
export const ADD_MOVIE_FAILURE = 'ADD_MOVIE_FAILURE'
export const ADD_MOVIE_RESET = 'ADD_MOVIE_RESET'
